apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: peregrine
spec:
  serviceName: peregrine
  replicas: 1
  template:
    metadata:
      labels:
        app: peregrine
    spec:
      initContainers:
      - name: init
        image: peregrinecms/peregrine-cms:develop
        command:
        - sh
        - -c
        - 'if [ ! -d /app1/sling ]; then tar -cf /app.tar /app && tar -xf /app.tar -C /app1 --strip 1; fi' 
        volumeMounts:
        - name: data
          mountPath: /app1
      containers:
        - name: peregrine
          image: peregrinecms/peregrine-cms:develop
          ports:
          - name: http
            containerPort: 8080
          volumeMounts:
          - name: data
            mountPath: /app
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 5Mi
      accessModes:
      - ReadWriteOnce
