apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gke-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: aemaacs-headwire-com-ip-address
    networking.gke.io/managed-certificates: gke-certificate-1,gke-certificate-2
spec:
  rules:
  - host: aemaacs.headwire.com
    http:
      paths:
      - backend:
          serviceName: apache-live-r14-peregrine
          servicePort: 80
  - host: stage-aemaacs.headwire.com
    http:
      paths:
      - backend:
          serviceName: apache-stage-r14-peregrine	
          servicePort: 80
