apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gke-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: esploranto-ip-address
    networking.gke.io/managed-certificates: gke-certificate-1,gke-certificate-2
spec:
  rules:
  - host: demo1-live.esploranto.com
    http:
      paths:
      - backend:
          serviceName: apache-live-demo1-peregrine
          servicePort: 80
  - host: demo1-stage.esploranto.com
    http:
      paths:
      - backend:
          serviceName: apache-stage-demo1-peregrine
          servicePort: 80
