apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gke-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: thetechprepper-com-ip-address
    networking.gke.io/managed-certificates: gke-certificate-2,gke-certificate-3
spec:
  rules:
  - host: www.thetechprepper.com
    http:
      paths:
      - backend:
          serviceName: apache-live-r3-peregrine
          servicePort: 80
  - host: stage.thetechprepper.com
    http:
      paths:
      - backend:
          serviceName: apache-stage-r3-peregrine	
          servicePort: 80
