kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: worker1-data-{{ template "fullname" . }}-0
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
  spec:
    capacity:
      storage: {{ .Values.peregrine.storage }}
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    local:
      path: /mnt/disk/vol2
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8sworker1
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: worker2-data-{{ template "fullname" . }}-0
    labels:
      app: {{ template "fullname" . }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: "{{ .Release.Name }}"
      heritage: "{{ .Release.Service }}"
  spec:
    capacity:
      storage: {{ .Values.peregrine.storage }}
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    local:
      path: /mnt/disk/vol2
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8sworker2
