kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: data-{{ template "fullname" . }}-0
  spec:
    capacity:
      storage: {{ .Values.peregrine.storage }}
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    local:
      path: /mnt/disk/vol1
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - yourworkerhostname
