apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: apache-author
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-author
  template:
    metadata:
      labels:
        app: apache-author
    spec:
      containers:
        - name: apache-author
          image: peregrinecms/apache-author
          ports:
          - name: http
            containerPort: 80
          env:
            - name: APACHE_PROXY_URL
              value: http://peregrine:8080/
            - name: APACHE_DOMAIN
              value: author.peregrine.cxm
