apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: apache-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-stage
  template:
    metadata:
      labels:
        app: apache-stage
    spec:
      containers:
        - name: apache-stage
          image: peregrinecms/apache-stage
          ports:
          - name: http
            containerPort: 80
          env:
            - name: APACHE_PROXY_URL
              value: http://peregrine:8080/
            - name: APACHE_DOMAIN
              value: stage.peregrine.cxm
