apiVersion: v1
kind: Service
metadata:
  name: "peregrine-{{ template "fullname" . }}"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"

spec:
  selector:
    app: {{ template "fullname" . }}
  ports:
  - name: http
    port: 80
    targetPort: 8080
