apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  serviceName: peregrine
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      initContainers:
      - name: init
        image: peregrinecms/peregrine-cms:stable
        command:
        - sh
        - -c
        - 'if [ ! -d /app1/sling ]; then tar -cf - /app | tar -C /app1 --strip 1 -xf -; fi' 
        volumeMounts:
        - name: data
          mountPath: /app1
      containers:
        - name: peregrine
          image: peregrinecms/peregrine-cms:stable
          env:
          - name: _JAVA_OPTIONS
            value: -Dos.version=4.14.127
          ports:
          - name: http
            containerPort: 8080
          volumeMounts:
          - name: data
            mountPath: /app
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 5Gi
      accessModes:
      - ReadWriteOnce
