apiVersion: v1
kind: ConfigMap
metadata:
  name: "stage-{{ template "fullname" . }}"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  APACHE_PROXY_URL: http://{{ .Release.Name }}-peregrine-0.peregrine-{{ .Release.Name }}-peregrine.{{ .Release.Namespace }}.svc.cluster.local:8080/
  APACHE_DOMAIN: {{ .Values.apache.stageDomain }}
  PEREGRINE_SITE: {{ .Values.peregrine.site }}
  K8S_NAMESPACE: {{ .Release.Namespace }}
